### ISSUE TITLE
is there anyway to generate actual spoofing signal and transmit it through sdr?

### ISSUE THREAD

**Issue by Imtiaz08** [pc-beast/aj-as-gnss#2]
Hi I am working on GNSS Spoofing and I have generated a spoofing signal in Matlab but when I transmit it says invalid preamble. Ca you provide any insights on this?

**Comment by pavnesh-c** [comment]
@Imtiaz08 can you mail me [here](mailto:2019kuec2037@iiitkota.ac.in) here with more details, so that we can have a discussion?
